export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './dashboardController.service';
import { DashboardControllerService } from './dashboardController.service';
export * from './measurementController.service';
import { MeasurementControllerService } from './measurementController.service';
export * from './peripheryConnectionController.service';
import { PeripheryConnectionControllerService } from './peripheryConnectionController.service';
export * from './timeRecordController.service';
import { TimeRecordControllerService } from './timeRecordController.service';
export * from './userManagementController.service';
import { UserManagementControllerService } from './userManagementController.service';
export const APIS = [AuthControllerService, DashboardControllerService, MeasurementControllerService, PeripheryConnectionControllerService, TimeRecordControllerService, UserManagementControllerService];
