/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TemperaStation } from './temperaStation';
import { Room } from './room';


export interface AccessPoint { 
    id?: string;
    temperaStations?: Set<TemperaStation>;
    room?: Room;
    enabled?: boolean;
    _new?: boolean;
    healthy?: boolean;
}

