/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AlertDto { 
    id?: string;
    message?: string;
    start?: string;
    end?: string;
    severity?: AlertDto.SeverityEnum;
    sensorType?: AlertDto.SensorTypeEnum;
}
export namespace AlertDto {
    export type SeverityEnum = 'INFO' | 'WARNING';
    export const SeverityEnum = {
        Info: 'INFO' as SeverityEnum,
        Warning: 'WARNING' as SeverityEnum
    };
    export type SensorTypeEnum = 'TEMPERATURE' | 'IRRADIANCE' | 'HUMIDITY' | 'NMVOC';
    export const SensorTypeEnum = {
        Temperature: 'TEMPERATURE' as SensorTypeEnum,
        Irradiance: 'IRRADIANCE' as SensorTypeEnum,
        Humidity: 'HUMIDITY' as SensorTypeEnum,
        Nmvoc: 'NMVOC' as SensorTypeEnum
    };
}


