/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuditLogDto { 
    id: string;
    timeStamp: string;
    triggeringUserName: string;
    actionType: AuditLogDto.ActionTypeEnum;
    affectedType: AuditLogDto.AffectedTypeEnum;
    message?: string;
}
export namespace AuditLogDto {
    export type ActionTypeEnum = 'CREATE' | 'EDIT' | 'DELETE' | 'LOGIN' | 'LOGOUT' | 'WARN' | 'LOAD';
    export const ActionTypeEnum = {
        Create: 'CREATE' as ActionTypeEnum,
        Edit: 'EDIT' as ActionTypeEnum,
        Delete: 'DELETE' as ActionTypeEnum,
        Login: 'LOGIN' as ActionTypeEnum,
        Logout: 'LOGOUT' as ActionTypeEnum,
        Warn: 'WARN' as ActionTypeEnum,
        Load: 'LOAD' as ActionTypeEnum
    };
    export type AffectedTypeEnum = 'USER' | 'PROJECT' | 'GROUP' | 'TEMPERA_STATION' | 'SENSOR' | 'MEASUREMENT' | 'ACCESS_POINT' | 'ROOM' | 'THRESHOLD' | 'TIME_RECORD';
    export const AffectedTypeEnum = {
        User: 'USER' as AffectedTypeEnum,
        Project: 'PROJECT' as AffectedTypeEnum,
        Group: 'GROUP' as AffectedTypeEnum,
        TemperaStation: 'TEMPERA_STATION' as AffectedTypeEnum,
        Sensor: 'SENSOR' as AffectedTypeEnum,
        Measurement: 'MEASUREMENT' as AffectedTypeEnum,
        AccessPoint: 'ACCESS_POINT' as AffectedTypeEnum,
        Room: 'ROOM' as AffectedTypeEnum,
        Threshold: 'THRESHOLD' as AffectedTypeEnum,
        TimeRecord: 'TIME_RECORD' as AffectedTypeEnum
    };
}


