/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeletionResponseDto { 
    responseType?: DeletionResponseDto.ResponseTypeEnum;
    message?: string;
}
export namespace DeletionResponseDto {
    export type ResponseTypeEnum = 'SUCCESS' | 'MANAGER' | 'GROUPLEAD' | 'ADMIN' | 'ERROR';
    export const ResponseTypeEnum = {
        Success: 'SUCCESS' as ResponseTypeEnum,
        Manager: 'MANAGER' as ResponseTypeEnum,
        Grouplead: 'GROUPLEAD' as ResponseTypeEnum,
        Admin: 'ADMIN' as ResponseTypeEnum,
        Error: 'ERROR' as ResponseTypeEnum
    };
}


