/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleUserDto } from './simpleUserDto';
import { SimpleProjectDto } from './simpleProjectDto';
import { GroupDetailsDto } from './groupDetailsDto';


export interface ExtendedGroupDto { 
    groupDetailsDto: GroupDetailsDto;
    activeProjects: Array<SimpleProjectDto>;
    members: Set<SimpleUserDto>;
}

