/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExternalRecordDto { 
    access_point_id?: string;
    tempera_station_id?: string;
    start?: string;
    duration?: number;
    mode?: ExternalRecordDto.ModeEnum;
    auto_update?: boolean;
}
export namespace ExternalRecordDto {
    export type ModeEnum = 'AVAILABLE' | 'MEETING' | 'OUT_OF_OFFICE' | 'DEEPWORK';
    export const ModeEnum = {
        Available: 'AVAILABLE' as ModeEnum,
        Meeting: 'MEETING' as ModeEnum,
        OutOfOffice: 'OUT_OF_OFFICE' as ModeEnum,
        Deepwork: 'DEEPWORK' as ModeEnum
    };
}


