/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SimpleUserDto } from './simpleUserDto';
import { GroupxProjectDto } from './groupxProjectDto';
import { SimpleGroupDto } from './simpleGroupDto';


export interface ExtendedGroupDto { 
    simpleGroupDto?: SimpleGroupDto;
    projects?: Set<GroupxProjectDto>;
    members?: Set<SimpleUserDto>;
}

