/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FrontendMeasurementDto { 
    value?: number;
    quality?: FrontendMeasurementDto.QualityEnum;
}
export namespace FrontendMeasurementDto {
    export type QualityEnum = 'GOOD' | 'MEDIOCRE' | 'POOR';
    export const QualityEnum = {
        Good: 'GOOD' as QualityEnum,
        Mediocre: 'MEDIOCRE' as QualityEnum,
        Poor: 'POOR' as QualityEnum
    };
}


