/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { Groupx } from './groupx';
import { GroupxProjectId } from './groupxProjectId';
import { Userx } from './userx';


export interface GroupxProject { 
    group?: Groupx;
    project?: Project;
    contributors?: Set<Userx>;
    id?: GroupxProjectId;
    active?: boolean;
    _new?: boolean;
}

