/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccessPoint } from './accessPoint';
import { Threshold } from './threshold';


export interface Room { 
    thresholds?: Set<Threshold>;
    accessPoint?: AccessPoint;
    id?: string;
    _new?: boolean;
}

