/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { GroupxProject } from './groupxProject';
import { TemperaStation } from './temperaStation';
import { Groupx } from './groupx';


export interface Userx { 
    username?: string;
    temperaStation?: TemperaStation;
    groupxProjects?: Set<GroupxProject>;
    groups?: Array<Groupx>;
    password?: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    enabled?: boolean;
    state?: Userx.StateEnum;
    stateVisibility?: Userx.StateVisibilityEnum;
    defaultProject?: Project;
    roles?: Set<Userx.RolesEnum>;
    id?: string;
    _new?: boolean;
}
export namespace Userx {
    export type StateEnum = 'AVAILABLE' | 'MEETING' | 'OUT_OF_OFFICE' | 'DEEPWORK';
    export const StateEnum = {
        Available: 'AVAILABLE' as StateEnum,
        Meeting: 'MEETING' as StateEnum,
        OutOfOffice: 'OUT_OF_OFFICE' as StateEnum,
        Deepwork: 'DEEPWORK' as StateEnum
    };
    export type StateVisibilityEnum = 'PUBLIC' | 'PRIVATE' | 'HIDDEN';
    export const StateVisibilityEnum = {
        Public: 'PUBLIC' as StateVisibilityEnum,
        Private: 'PRIVATE' as StateVisibilityEnum,
        Hidden: 'HIDDEN' as StateVisibilityEnum
    };
    export type RolesEnum = 'ADMIN' | 'MANAGER' | 'GROUPLEAD' | 'EMPLOYEE';
    export const RolesEnum = {
        Admin: 'ADMIN' as RolesEnum,
        Manager: 'MANAGER' as RolesEnum,
        Grouplead: 'GROUPLEAD' as RolesEnum,
        Employee: 'EMPLOYEE' as RolesEnum
    };
}


