/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserxDto { 
    username: string;
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    enabled?: boolean;
    roles?: Set<UserxDto.RolesEnum>;
}
export namespace UserxDto {
    export type RolesEnum = 'ADMIN' | 'MANAGER' | 'GROUPLEAD' | 'EMPLOYEE';
    export const RolesEnum = {
        Admin: 'ADMIN' as RolesEnum,
        Manager: 'MANAGER' as RolesEnum,
        Grouplead: 'GROUPLEAD' as RolesEnum,
        Employee: 'EMPLOYEE' as RolesEnum
    };
}


