package at.qe.skeleton.model;

import at.qe.skeleton.model.enums.SensorType;
import at.qe.skeleton.model.enums.Unit;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;

import java.util.List;
import java.util.Objects;

@Entity
public class Sensor {

  @EmbeddedId private SensorId sensorId;

  @ManyToOne(optional = false)
  @MapsId("temperaId")
  @JoinColumn(name = "tempera_id")
  private TemperaStation temperaStation;

  @OneToMany(mappedBy = "sensor", cascade = CascadeType.PERSIST, fetch = FetchType.LAZY, orphanRemoval = true)
  List<Measurement> measurements;

  @Enumerated(EnumType.STRING) // necessary to store the enum as a string in the database
  private SensorType sensorType;

  @Enumerated(EnumType.STRING) // necessary to store the enum as a string in the database
  private Unit unit;

  /**
   * Constructor for Sensor. Automatically sets the compositeId consisting of the temperaStationId
   * and the sensorId. The latter is automatically generated by the database.
   *
   * @param sensorType must not be null
   * @param unit must not be null
   * @param temperaStation must not be null
   */
  public Sensor(
      @NotNull SensorType sensorType, @NotNull Unit unit, @NotNull TemperaStation temperaStation) {
    this.sensorType = Objects.requireNonNull(sensorType, "sensorType must not be null");
    this.unit = Objects.requireNonNull(unit, "unit must not be null");
    this.temperaStation = Objects.requireNonNull(temperaStation, "temperaStation must not be null");
    SensorId compositeId = new SensorId();
    compositeId.setTemperaId(temperaStation.getId());
    this.sensorId = compositeId;
  }

  public void setTemperaStation(@NotNull TemperaStation temperaStation) {
    this.temperaStation = Objects.requireNonNull(temperaStation, "temperaStation must not be null");
  }

  protected Sensor() {}

  public void setId(SensorId sensorId) {
    this.sensorId = sensorId;
  }

  public TemperaStation getTemperaStation() {
    return temperaStation;
  }

  public SensorId getId() {
    return sensorId;
  }

  public SensorType getSensorType() {
    return sensorType;
  }

  public void setSensorType(@NotNull SensorType sensorType) {
    this.sensorType = Objects.requireNonNull(sensorType, "sensorType must not be null");
  }

  public void addMeasurement(Measurement measurement) {
    this.measurements.add(measurement);
    measurement.setSensor(this);
  }

  public void removeMeasurement(Measurement measurement) {
    this.measurements.remove(measurement);
    measurement.setSensor(null);
  }

  public List<Measurement> getMeasurements() {
    return this.measurements;
  }

  public SensorId getSensorId() {
    return sensorId;
  }

  public Unit getUnit() {
    return unit;
  }

  public void setUnit(@NotNull Unit unit) {
    this.unit = Objects.requireNonNull(unit, "unit must not be null");
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof Sensor other)) return false;
    return sensorId.equals(other.sensorId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sensorId);
  }

  @Override
  public String toString() {
    return "Sensor{compositeId: %s sensorType: %s} \n"
        .formatted(sensorId, sensorType);
  }
}
